import { SportDefinition } from './types';

export const SPORTS_CATALOGUE: SportDefinition[] = [
  {
    id: 'football',
    name: 'Football',
    tagline: 'Precision Footwork & Agility Mechanics',
    description: 'Drills targeting balance, athletic ready-stance, lateral changes of direction, and controlled touch cadence.',
    accentColor: '#57E5D6',
    drills: [
      {
        id: 'football_lateral_footwork',
        sportId: 'football',
        title: 'Lateral Footwork & Stance',
        shortDesc: 'Athletic stance, controlled side steps, direction-change timing, and upright balance.',
        mode: 'pose',
        supportedObservations: ['Knee Flexion Angle', 'Hip Leveling', 'Lateral Center of Mass Shift'],
        setupSteps: [
          'Position device 7-9 feet away, framing full body from head to feet.',
          'Start in balanced athletic stance with knees softly bent (130°-150°).',
          'Take 2 controlled steps left, pause momentarily, then 2 steps right.',
        ],
        rules: [
          {
            id: 'stance_bend',
            name: 'Athletic Stance Knee Bend',
            minConfidence: 0.60,
            targetAngleMin: 125,
            targetAngleMax: 155,
            targetDwellMs: 250,
            hysteresisExitDelta: 8,
          },
        ],
        defaultDurationSec: 60,
        targetIntervalCount: 8,
        category: 'footwork',
      },
      {
        id: 'football_agility_sequence',
        sportId: 'football',
        title: 'Agility Step Sequence',
        shortDesc: 'User-selected step pattern with visual tempo cues and steady recovery.',
        mode: 'timed',
        supportedObservations: ['Cadence Rhythm', 'Step Tempo', 'Break Compliance'],
        setupSteps: [
          'Clear a 6x6 foot floor space.',
          'Follow the on-screen rhythm for quick foot taps in place or around markers.',
          'Maintain relaxed shoulders and light contact with balls of feet.',
        ],
        rules: [],
        defaultDurationSec: 45,
        targetIntervalCount: 6,
        category: 'footwork',
      },
      {
        id: 'football_ball_control',
        sportId: 'football',
        title: 'Ball-Control Touches',
        shortDesc: 'Timed touch practice with manual tap counting by default. Optional ball detection requires verified threshold.',
        mode: 'pose-plus-optional-ball',
        supportedObservations: ['Touch Cadence (Manual/Optional CV)', 'Stance Stability'],
        setupSteps: [
          'Place football directly in front of you.',
          'Alternate gentle sole taps or inside touches at your own controlled rhythm.',
          'Tap the screen or press spacebar to record touches; or enable experimental vision detection.',
        ],
        rules: [],
        defaultDurationSec: 60,
        targetIntervalCount: 20,
        category: 'touches',
      },
      {
        id: 'football_passing_targets',
        sportId: 'football',
        title: 'Passing Target Accuracy',
        shortDesc: 'Aim at visible target zones and confirm successful contacts manually.',
        mode: 'manual',
        supportedObservations: ['Target Zone Selection', 'Manual Contact Confirmation'],
        setupSteps: [
          'Pick left or right target marker in your practice zone.',
          'Perform a crisp ground pass toward the selected zone.',
          'Tap confirm whenever your pass accurately hits the target zone.',
        ],
        rules: [],
        defaultDurationSec: 90,
        targetIntervalCount: 10,
        category: 'passing',
      },
    ],
  },
  {
    id: 'basketball',
    name: 'Basketball',
    tagline: 'Stance, Defensive Sliding & Shooting Rehearsal',
    description: 'Drills emphasizing defensive posture, lateral slide deceleration, dribble rhythm, and mechanics rehearsal.',
    accentColor: '#B8A2FF',
    drills: [
      {
        id: 'basketball_athletic_stance',
        sportId: 'basketball',
        title: 'Athletic Defensive Stance',
        shortDesc: 'Knee and hip bend range, upright chest control, without rewarding unsupported fatigue holds.',
        mode: 'pose',
        supportedObservations: ['Knee Flexion Angle', 'Torso Lean Angle', 'Stance Retention Interval'],
        setupSteps: [
          'Face camera 7-8 feet back, showing full stance.',
          'Drop into active defensive stance with knees bent (120°-145°).',
          'Keep chest proud and arms wide; hold for 3-5 seconds, stand tall to recover.',
        ],
        rules: [
          {
            id: 'basketball_knee_flex',
            name: 'Defensive Knee Flexion',
            minConfidence: 0.60,
            targetAngleMin: 115,
            targetAngleMax: 145,
            targetDwellMs: 400,
            hysteresisExitDelta: 10,
          },
        ],
        defaultDurationSec: 60,
        targetIntervalCount: 6,
        category: 'stance',
      },
      {
        id: 'basketball_defensive_slides',
        sportId: 'basketball',
        title: 'Defensive Lateral Slides',
        shortDesc: 'Lateral movement, stance retention, and controlled direction deceleration.',
        mode: 'pose',
        supportedObservations: ['Hip-Knee Angle in Motion', 'Lateral Deceleration', 'Stance Retention'],
        setupSteps: [
          'Clear 8-10 feet laterally.',
          'Stay low and slide 3 paces to the left without crossing feet.',
          'Decelerate, hold for 1 count, then slide 3 paces to the right.',
        ],
        rules: [
          {
            id: 'slide_stance',
            name: 'Slide Stance Maintenance',
            minConfidence: 0.60,
            targetAngleMin: 120,
            targetAngleMax: 155,
            targetDwellMs: 250,
            hysteresisExitDelta: 8,
          },
        ],
        defaultDurationSec: 60,
        targetIntervalCount: 6,
        category: 'slides',
      },
      {
        id: 'basketball_dribble_rhythm',
        sportId: 'basketball',
        title: 'Dribble Rhythm Cadence',
        shortDesc: 'Timed cadence with manual confirmation by default; optional ball events expose confidence.',
        mode: 'pose-plus-optional-ball',
        supportedObservations: ['Dribble Beat (Manual/Optional CV)', 'Stance Height'],
        setupSteps: [
          'Assume athletic stance with basketball in dominant hand.',
          'Execute rhythmic low dribbles at steady beats.',
          'Confirm cadence manually or allow optional ball detection if enabled.',
        ],
        rules: [],
        defaultDurationSec: 60,
        targetIntervalCount: 30,
        category: 'touches',
      },
      {
        id: 'basketball_shooting_rehearsal',
        sportId: 'basketball',
        title: 'Shooting-Form Rehearsal',
        shortDesc: 'Deterministic phases using shoulder, elbow, wrist, hip, and knee landmarks. Form rehearsal only; does not predict made baskets.',
        mode: 'pose',
        supportedObservations: ['Elbow Alignment Angle', 'Set-Point Dwell', 'Follow-Through Extension'],
        setupSteps: [
          'Stand 45 degrees to camera with shooting arm visible.',
          'Begin at Dip/Gather with elbow bent (~80°-100°).',
          'Elevate through Set Point to full follow-through extension (~160°-175°).',
        ],
        rules: [
          {
            id: 'shooting_elbow_gather',
            name: 'Gather Phase Elbow Flexion',
            minConfidence: 0.60,
            targetAngleMin: 70,
            targetAngleMax: 105,
            targetDwellMs: 250,
            hysteresisExitDelta: 8,
          },
          {
            id: 'shooting_elbow_release',
            name: 'Release Phase Arm Extension',
            minConfidence: 0.60,
            targetAngleMin: 155,
            targetAngleMax: 180,
            targetDwellMs: 200,
            hysteresisExitDelta: 10,
          },
        ],
        defaultDurationSec: 60,
        targetIntervalCount: 8,
        category: 'shooting_rehearsal',
      },
    ],
  },
];
